# ArgoCD Installation Request for ardenone-cluster
#
# This manifest grants devpod ServiceAccount permissions to install ArgoCD.
# A cluster-admin MUST apply this with:
#   kubectl apply -f cluster-configuration/ardenone-cluster/argocd/ARGOCD_SETUP_REQUEST.yml
#
# After this RBAC is applied, from the devpod run:
#   kubectl apply -f cluster-configuration/ardenone-cluster/argocd/argocd-install.yml
#
# The argocd-install.yml contains the official ArgoCD installation manifest from:
# https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
#
# VERIFICATION STATUS (2026-02-05 12:59 UTC):
# - ArgoCD namespace: NOT FOUND (confirmed via kubectl get namespace argocd)
# - argocd-manager-role ClusterRole: EXISTS (wildcard permissions, reusable)
# - argocd-manager-role-binding: EXISTS but bound to kube-system:argocd-manager
# - devpod ServiceAccount permissions: INSUFFICIENT for creating ClusterRoleBindings
# - ClusterRoleBinding devpod-argocd-manager: NOT FOUND (needs cluster-admin action)
# - ArgoCD CRDs: Partial (4 argoproj.io CRDs found, full installation incomplete)
# - BLOCKER: Installation REQUIRES cluster-admin to create ClusterRoleBinding
# - STATUS: AWAITING CLUSTER-ADMIN ACTION (bead mo-1fbe tracks this requirement)
# - ACTION: Run `kubectl create clusterrolebinding devpod-argocd-manager --clusterrole=argocd-manager-role --serviceaccount=devpod:default`
#
# INSTALLATION INSTRUCTIONS (for cluster-admin):
#   kubectl apply -f cluster-configuration/ardenone-cluster/argocd/ARGOCD_SETUP_REQUEST.yml
#
# Then from devpod:
#   kubectl apply -f cluster-configuration/ardenone-cluster/argocd/argocd-install.yml

---
# Step 1: Create ClusterRoleBinding to grant devpod access to existing argocd-manager-role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devpod-argocd-manager
subjects:
- kind: ServiceAccount
  name: default
  namespace: devpod
roleRef:
  kind: ClusterRole
  name: argocd-manager-role
  apiGroup: rbac.authorization.k8s.io

---
# Step 2: Create the argocd namespace
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
