# ArgoCD Installation Request for ardenone-cluster
#
# This manifest grants devpod ServiceAccount permissions to install ArgoCD.
# A cluster-admin MUST apply this with:
#   kubectl apply -f cluster-configuration/ardenone-cluster/argocd/ARGOCD_SETUP_REQUEST.yml
#
# After this RBAC is applied, from the devpod run:
#   kubectl apply -f ../../k8s/argocd-install-manifest.yaml
#
# The argocd-install-manifest.yaml contains the official ArgoCD installation manifest from:
# https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
#
# VERIFICATION STATUS (2026-02-04):
# - ArgoCD namespace: NOT FOUND
# - RBAC permissions: NOT APPLIED (requires cluster-admin)
# - Installation: BLOCKED until cluster-admin applies this manifest

---
# Step 1: Grant devpod ServiceAccount permission to manage ArgoCD resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-installer
rules:
# Namespace management
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "get", "list", "watch"]

# Custom Resource Definitions (for ArgoCD CRDs)
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "list", "watch", "patch", "update"]

# ArgoCD namespace resources (deployments, services, configmaps, secrets, etc.)
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services", "serviceaccounts", "persistentvolumeclaims"]
  verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]

- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]

- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]

- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies", "ingresses"]
  verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]

# RBAC for ArgoCD service accounts
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["create", "get", "list", "watch", "patch", "update", "delete", "escalate", "bind"]

# ArgoCD CRs
- apiGroups: ["argoproj.io"]
  resources: ["applications", "appprojects", "applicationsets", "argocds"]
  verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]

# Scheduling for priority class
- apiGroups: ["scheduling.k8s.io"]
  resources: ["priorityclasses"]
  verbs: ["create", "get", "list", "watch", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devpod-argocd-installer
subjects:
- kind: ServiceAccount
  name: default
  namespace: devpod
roleRef:
  kind: ClusterRole
  name: argocd-installer
  apiGroup: rbac.authorization.k8s.io

---
# Step 2: Create the argocd namespace
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
